version: '3'

services:

  nginx:
    image: nginx:alpine
    build: docker_images/nginx
    volumes:
      - static:/app/staticfiles
      - media:/app/media
    links:
      - web:web
    ports:
      - "80:80"
    networks:
      - mynetwork

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  web:
    build: .
    volumes:
      - static:/app/staticfiles
      - media:/app/media
    entrypoint: /app/entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    networks:
      - mynetwork



volumes:
  postgres_data:
  static:
  media:

networks:
  mynetwork:
